# Generated by Django 4.1.2 on 2022-10-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pre_registro_paciente',
            new_name='registro_paciente',
        ),
    ]
