# Generated by Django 4.1.2 on 2022-11-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_registro', '0002_rename_pre_registro_paciente_registro_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='pre_registro_paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DatosGenerales', models.CharField(max_length=400)),
                ('AntecedentesPersonales', models.SlugField(max_length=400)),
                ('AntecedentesFamiliares', models.TextField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='registro_paciente',
        ),
    ]
